# Shell variables
# Generated by 'wal'
wallpaper='/home/evariste/Dotfiles/wallpapers/pywallpaper.jpg'

# Special
background='#021E25'
foreground='#adc2b8'
cursor='#adc2b8'

# Colors
color0='#021E25'
color1='#B26E4E'
color2='#2F8379'
color3='#608A7A'
color4='#AA9473'
color5='#FA8F44'
color6='#E5965F'
color7='#adc2b8'
color8='#798780'
color9='#B26E4E'
color10='#2F8379'
color11='#608A7A'
color12='#AA9473'
color13='#FA8F44'
color14='#E5965F'
color15='#adc2b8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
